export const PHONES_REQUEST = 'PHONES_REQUEST';
export const PHONES_RECEIVED = 'PHONES_RECEIVED';
export const NEW_PHONE_CREATED = 'NEW_PHONE_CREATED';
export const PHONE_CHANGED = 'PHONE_CHANGED';
export const PHONE_REMOVED = 'PHONE_REMOVED';